FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY . /app

# Instala dependências do projeto e inclui mlflow via pyproject
RUN pip install -e .

EXPOSE 5000

CMD ["mlflow", "ui", "--backend-store-uri", "file:///app/experiments/mlruns", "--default-artifact-root", "file:///app/experiments/mlruns", "--host", "0.0.0.0", "--port", "5000"]
